#
# Hare build
#
---
- name: dynamically load variables depending on the OS type
  include_vars: '{{ item  }}'
  with_first_found: '{{ ansible_os_family }}.yml'
  tags: hare

- name: install Hare build-time dependencies
  package:
    state: present
    name:  '{{ hare_build_deps_pkgs }}'
  tags: hare
