#
# iSCSI initiator tasks
#
---
- name: configure iSCSI initiator
  block:
    - name: deploy iscsi-initiator-cmu.service
      template:
        src: iscsi-initiator-cmu.service.j2
        dest: /etc/systemd/system/iscsi-initiator-cmu.service

    - name: deploy iscsi-initiator-ssus.service
      template:
        src: iscsi-initiator-ssus.service.j2
        dest: /etc/systemd/system/iscsi-initiator-ssus.service

    - name: deploy iscsi-initiator-ssu1.service
      template:
        src: iscsi-initiator-ssu1.service.j2
        dest: /etc/systemd/system/iscsi-initiator-ssu1.service

    - name: deploy iscsi-initiator-ssu2.service
      template:
        src: iscsi-initiator-ssu2.service.j2
        dest: /etc/systemd/system/iscsi-initiator-ssu2.service

    - name: update systemd service configs
      systemd: daemon_reload=yes
  tags: iscsi-initiator
