#
# iSCSI target tasks
#
---
- name: configure iSCSI target
  block:
    - name: mkdir iscsi image location
      file:
        path: /var/target/images
        state: directory

    - name: load setup-iscsi-target config
      template:
        src: setup-iscsi-target.conf.j2
        dest: /tmp/setup-iscsi-target.conf

    - name: load setup-iscsi-target script
      copy:
        src: setup-iscsi-target
        dest: /tmp/setup-iscsi-target
        mode: '0755'

    - name: run setup-iscsi-target script
      command: /tmp/setup-iscsi-target {{ iscsi_backstore_type }}
      args:
        creates: /etc/target/saveconfig.json

    - name: load iSCSI target config
      service: name=target state=started enabled=yes
  tags: iscsi-target
