---
mero_build_deps_pkgs:
  - asciidoc
  - autoconf
  - automake
  - binutils
  - binutils-devel
  - createrepo            # for lustre-client-devel rpm
  - gcc
  - gcc-c++
  - gccxml
  - glibc-headers
  - kernel-devel
  - libaio
  - libaio-devel
  - libtool
  - libuuid-devel
  - libyaml
  - libyaml-devel
  - make
  - perl
  - perl-File-Find-Rule
  - perl-File-Slurp
  - perl-IO-All
  - perl-List-MoreUtils
  - perl-XML-LibXML
  - perl-autodie
  - python-ply
  - python-devel
  - PyYAML                # required only for tests (m0hagen)
  - rpm-build
  - systemd-devel

mero_build_deps_python3_pkgs:
  - python36
  - python36-devel
  - python36-numpy   # performance tools addb2 analisys
  - python36-plumbum # performance tools addb2 analisys
  - python36-ply
  - python36-PyYAML
  - python36-tqdm    # performance tools addb2 analisys

mero_doc_deps_pkgs:
  - python36-pip
  # Anssible requires setuptools from python 2.7 in order to use 'pip' module
  - python-setuptools
  # there is no plantuml in Centos7/EPEL repos, using compatible version from
  # Fedora 27
  - 'http://archives.fedoraproject.org/pub/archive/fedora/linux/releases/27/Everything/x86_64/os/Packages/p/plantuml-8033-6.fc27.noarch.rpm'

mero_doc_pip_modules:
  - sphinx
  - sphinxcontrib-plantuml

lustre_build_deps_pkgs:
  - patch
